---
title: "data_wrangling_ii Reading Data from the Web"
author: "Boya Guo"
date: "2018/10/11"
output: github_document
---
```{r}
library(tidyverse)
library(rvest)
library(httr)
```

### Scrape a table 

First get the html 

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)

drug_use_xml
```

Get the table from the HTML
```{r}
drug_use_xml %>%
  html_nodes(css = "table") %>%
  .[[1]] %>%
  html_table() %>%
    slice(-1)  %>%
  as_tibble()
```

### Learning Assessment

```{r}
nyc_cost = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>%
  html_nodes(css = "table") %>%
  .[[1]] %>%
  html_table(header = TRUE)
```
header = TRUE first variable will be the name you care about 

### CSS Selectors: Harry Poter example 

```{r}
hpsaga_html = read_html("https://www.imdb.com/list/ls000630791/") %>%
  hpsaga_html %>%
  html_nodes(".lister-item-header a") %>%
  html_text()

gross_rev_vec = hpsaga_html %>%
  html_nodes(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = hpsaga_html %>%
  html_nodes(".runtime") %>%
  html_text()

hpsaga_df = tibble(
  title = title_vec,
  rev = gross_rev_vec,
  runtime = runtime_vec
)
```

### Learning Assessment 

```{r}
rl = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

### API 

Get water data 

```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")
```

Import JASON file 

```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

### BRFSS

```{r}
brfss_smart2010 = 
  GET("https://data.cdc.gov/api/views/acme-vg9e/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```

### Pokemon API 
```{r}
poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name

poke$height

poke$abilities
```