---
title: "Tidy Data"
author: "Boya Guo"
date: "9/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
`````

## Gather

Pulse data 

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
pulse_data %>% View
`````

This isn't tidy yet...

```{r}
pulse_data %>%
gather(key ="visit",value ="bdi_score", bdi_score_bl:bdi_score_12m) %>% View
````


```{r}
pulse_tidy=pulse_data %>%
gather(key = "visit",value ="bdi_score", bdi_score_bl:bdi_score_12m) %>% View("tidy")

pulse_data %>% View("nontidy")
````

Illustrate: separate,mutate and replace: 

```{r}
pulse_tidy_data = gather(pulse_data, key = visit, value = bdi, bdi_score_bl:bdi_score_12m)

separate(pulse_tidy_data, visit, into = c("remove_1", "remove_2", "visit"), sep = "_")
````

All together, the data import/cleaning pipline is: 

```{r}
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>% 
  gather(key = "visit", value = "bdi_score", bdi_score_bl:bdi_score_12m) %>% 
  separate(visit, into = c("bdi_str", "score_str", "visit"), sep = "_") %>% 
  select(-bdi_str, -score_str) %>% 
  mutate(visit = replace(visit, visit == "bl", "00m"))
```
## Revisit litters dataset 

```{r}
litters_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>% 
  separate(group, into = c("dose", "day"), 3)
```
The number 3 indicates the location to separate. 

## Learning Assessment

```{r}
litters_data %>% 
  select(litter_number, ends_with("weight")) %>% 
  gather(key = gd, value = weight, gd0_weight:gd18_weight) %>%
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
```

## Spread (a reverse operation of gather)

Create analysis_result

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
```

Make it readable:

```{r}
analysis_result %>% 
  spread(key = time, value = mean) %>% 
  knitr::kable()
```
knitr makes the table more presentable. 

